name: metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # general metrics
      - name: general
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.general.svg
      # comment reactions
      - name: comments
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.comments.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
      # language activity
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: >-
            html, css, tex, jupyter notebook
      # lines added and removed
      - name: lines
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
